"""produtos crud

Revision ID: 3dcce72382ec
Revises: b438e1860821
Create Date: 2025-12-09 10:20:21.293329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcce72382ec'
down_revision = 'b438e1860821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loja_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['loja_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loja_id')

    # ### end Alembic commands ###
