"""Fix Store model fields

Revision ID: 7f92e35889eb
Revises: af92596962c4
Create Date: 2025-11-19 10:29:02.594765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f92e35889eb'
down_revision = 'af92596962c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celularp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nextreferencia', sa.String(), nullable=True))
        batch_op.drop_column('telefone')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.INTEGER(), nullable=True))
        batch_op.drop_column('nextreferencia')
        batch_op.drop_column('celularp')

    # ### end Alembic commands ###
