"""add endereço

Revision ID: 8152ed2611cc
Revises: 
Create Date: 2025-11-17 10:44:12.246185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8152ed2611cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
