"""Create store table

Revision ID: b438e1860821
Revises: 7f92e35889eb
Create Date: 2025-11-19 11:07:50.745265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b438e1860821'
down_revision = '7f92e35889eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(), nullable=True))
        batch_op.drop_column('endereço')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereço', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
